apiVersion: v1
kind: Service
metadata:
  name: lurus-www
  namespace: lurus-www
  labels:
    app.kubernetes.io/name: lurus-www
    app.kubernetes.io/part-of: lurus
spec:
  selector:
    app.kubernetes.io/name: lurus-www
  ports:
    - name: http
      port: 3000
      targetPort: http
